package com.gridnine.Tests;

public enum FilterType {
    FILTER_FLIGHTS_WITH_DEPARTURE_IS_BEFORE_NOW,
    FILTER_FLIGHTS_WITH_ARRIVAL_IS_BEFORE_DEPARTURE,
    FILTER_FLIGHTS_WITH_TOTAL_ON_EARTH_TIME_IS_GREATER_THAN_2_HOURS

}
